/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import static Principal.JPEGHandler.runHandler;
import com.sun.prism.paint.Color;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        O4 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        NF = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        O1 = new javax.swing.JRadioButton();
        O2 = new javax.swing.JRadioButton();
        O3 = new javax.swing.JRadioButton();
        O5 = new javax.swing.JRadioButton();
        O6 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();

        jButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton3.setFont(new java.awt.Font("Arial Narrow", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Agregar Imagen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        O4.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O4);
        O4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O4.setForeground(new java.awt.Color(255, 255, 255));
        O4.setText("JPEG a BMP / BMP a JPEG");
        O4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Fotos");
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Funciones");

        jButton4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton4.setFont(new java.awt.Font("Arial Narrow", 3, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Seleccionar Imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        NF.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        NF.setForeground(new java.awt.Color(255, 255, 255));
        NF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Imagen Seleccionada");

        O1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O1);
        O1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O1.setForeground(new java.awt.Color(255, 255, 255));
        O1.setText("Rojo / Verde / Azul / Sepía");
        O1.setActionCommand("Rojo / Verde / Azul / Sepía");
        O1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O1ActionPerformed(evt);
            }
        });

        O2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O2);
        O2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O2.setForeground(new java.awt.Color(255, 255, 255));
        O2.setText("JPEG a BMP / BMP a JPEG");
        O2.setActionCommand("JPEG a BMP / BMP a JPEG");
        O2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O2ActionPerformed(evt);
            }
        });

        O3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O3);
        O3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O3.setForeground(new java.awt.Color(255, 255, 255));
        O3.setText("Modificar Imagen");
        O3.setActionCommand("Modificar Imagen");
        O3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O3ActionPerformed(evt);
            }
        });

        O5.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O5);
        O5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O5.setForeground(new java.awt.Color(255, 255, 255));
        O5.setText("Blanco / Negro");
        O5.setActionCommand("Blanco / Negro");
        O5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O5ActionPerformed(evt);
            }
        });

        O6.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup4.add(O6);
        O6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        O6.setForeground(new java.awt.Color(255, 255, 255));
        O6.setText("Copia JPEG");
        O6.setActionCommand("Copia JPEG");
        O6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton5.setFont(new java.awt.Font("Arial Narrow", 3, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Ejecutar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 220, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(0, 221, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(O1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(O2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(O3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(O5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(O6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(O2)
                .addGap(18, 18, 18)
                .addComponent(O6)
                .addGap(18, 18, 18)
                .addComponent(O1)
                .addGap(18, 18, 18)
                .addComponent(O3)
                .addGap(18, 18, 18)
                .addComponent(O5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

            JFileChooser A = new JFileChooser();
            A.setMultiSelectionEnabled(true);
            A.setFileSelectionMode(JFileChooser.FILES_ONLY);

            FileNameExtensionFilter img = new FileNameExtensionFilter("Archivos JPEG & BMP", "jpg","jpeg","bmp");
            A.setFileFilter(img);

            int s = A.showOpenDialog(this);

            if (s!= JFileChooser.CANCEL_OPTION) {

                foto = A.getSelectedFile();

                NF.setText(foto.getPath());
                int i = foto.getName().lastIndexOf(".");
                ext=foto.getName().substring(i);
                
            }
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void O1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O1ActionPerformed

    private void O2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O2ActionPerformed

    private void O3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O3ActionPerformed

    private void O4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O4ActionPerformed

    private void O5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O5ActionPerformed

    private void O6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_O6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      if(buttonGroup4.getSelection()==null || foto==null){
          JOptionPane.showMessageDialog(null, "Seleccione una categoría en la lista antes de continuar y asegurese de haber seleccionado una imagen.", "Error", JOptionPane.WARNING_MESSAGE);
          System.out.println(Color.BLUE);
      }else{
        String seleccion=buttonGroup4.getSelection().getActionCommand();
        System.out.println(seleccion);
        
        switch(seleccion){
            case "JPEG a BMP / BMP a JPEG":
                if(ext.equalsIgnoreCase(".jpg") || ext.equalsIgnoreCase(".jpeg") ){
                    JPEGtoBMPImage A=new JPEGtoBMPImage(foto.getName());
                    try {
                        runHandler(A);
                    } catch (Exception ex) {
                    }
            
                }else{
                   if(ext.equalsIgnoreCase(".bmp")){
                    BMPtoJPEGImage B=new BMPtoJPEGImage(foto.getName());
                    try {
                        runHandler(B);
                    } catch (Exception ex) {
                    }
                   }else{
                      JOptionPane.showMessageDialog(null, "Seleccione un archivo con el formato soportado.", "Error", JOptionPane.WARNING_MESSAGE); 
                   }
                }
                break;
                
            
            case "Copia JPEG":
                if(ext.equalsIgnoreCase(".jpg") || ext.equalsIgnoreCase(".jpeg") ){
                    JPEGImageCopy C=new JPEGImageCopy(foto.getName());
                    try {
                        runHandler(C);
                    } catch (Exception ex) {
                    }
                }else{
                   JOptionPane.showMessageDialog(null, "Esta función solo acepta archivos .jpeg. Seleccione un archivo con el formato soportado.", "Error", JOptionPane.WARNING_MESSAGE); 
                }
                break;
            
            case "Rojo / Verde / Azul / Sepía":
                if(ext.equalsIgnoreCase(".jpg") || ext.equalsIgnoreCase(".jpeg") ){
                    JPEGImageHandlerColors C=new JPEGImageHandlerColors(foto.getName());
                    try {
                        runHandler(C);
                    } catch (Exception ex) {
                    }
                }else{
                   JOptionPane.showMessageDialog(null, "Esta función solo acepta archivos .jpeg. Seleccione un archivo con el formato soportado.", "Error", JOptionPane.WARNING_MESSAGE); 
                }
                break;
                
            case "Blanco / Negro":
                if(ext.equalsIgnoreCase(".jpg") || ext.equalsIgnoreCase(".jpeg") ){
                    JPEGImageHandlerBN C=new JPEGImageHandlerBN(foto.getName());
                    try {
                        runHandler(C);
                    } catch (Exception ex) {
                    }
                }else{
                   JOptionPane.showMessageDialog(null, "Esta función solo acepta archivos .jpeg. Seleccione un archivo con el formato soportado.", "Error", JOptionPane.WARNING_MESSAGE); 
                }
                break;
                
            case "Modificar Imagen":
               if(ext.equalsIgnoreCase(".jpg") || ext.equalsIgnoreCase(".jpeg") ){
                    JPEGImageHandlerRotator C=new JPEGImageHandlerRotator(foto.getName());
                    try {
                        runHandler(C);
                    } catch (Exception ex) {
                    }
                }else{
                   JOptionPane.showMessageDialog(null, "Esta función solo acepta archivos .jpeg. Seleccione un archivo con el formato soportado.", "Error", JOptionPane.WARNING_MESSAGE); 
                }
                break; 
        }
      }
      
    }//GEN-LAST:event_jButton5ActionPerformed

    public static File foto; //Foto en que se va a realizar la manipulación
    String ext; //Extensión de la foto
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JLabel NF;
    private javax.swing.JRadioButton O1;
    private javax.swing.JRadioButton O2;
    private javax.swing.JRadioButton O3;
    private javax.swing.JRadioButton O4;
    private javax.swing.JRadioButton O5;
    private javax.swing.JRadioButton O6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
